language: objective-c
osx_image: xcode11.3
xcode_project: LoginPush.xcodeproj
xcode_scheme: LoginPush
xcode_destination: platform=IOS Simulator,OS=12.1,name=iPhone X

before_install:
- chmod +x travis/add-key.sh 
- chmod +x travis/build.sh 
- chmod +x travis/remove-key.sh 


