language: objective-c
osx_image: xcode11.3
xcode_project: LoginPush.xcodeproj
xcode_scheme: LoginPush
xcode_destination: platform=IOS Simulator,OS=12.2,name=iPhone X
env:
  global:
    secure: Ue9BcJDjujj9nYCIceNCdaJwjdkjjT3buj5reAGjDAkL6pgtRS1Hglu6+eKpgvfdhpo3O8d7zu3oBUUSjyVEnYp4CKeI37WArbqKqf4mR+EnAzPm8QzA1InZC9xIuSTAsLOgCOLDavZM+DEj+xHE+H2elnZB6RmbwtBZi4c27iXiYh/QPZw3q4SHIBmEILNSIaifcXuDRjqm6shGUBJkto0wKV63cpB2zS97/tpYG+sXTrUlh72Apn803GqMcchrhqwKYSBq7n5DOKKjECcWLXxvbWiKXLxGwEWg9rEDFdtCybbjHP5Pf9TIQAWVp+ZTycLzld7I6M66KqwlR1rSYgD56uc2IexPN8y8Bpt+COl/9AcXAi175rHATuz86AyrpNKVhSH7XtPIdbV0jldibZCeg7J005hcBipKIn1NQrY6NYT4Zc39mBOJLPQpODhfmWtsw/saH6G2V8SA7VTTWmFB4toZb6dJ3z0aXz4k/OJMMsx4p5Id6IKlBPDmsuVfKdnPF+TSqaXr06vdIo5IGwp/BvLtEyV/NA+6PWTyIMo/TeRZAfGTIdQ19aR5ZRzIPo6ekEqqjmHX8AvferE017O3Hbm6rCKccR0+7JcQobnC/Y/uBwD/lGX/GZnHzWzSZV/kTNP3RC4+z2YZvb6Cx+42rop4t3sT2aXE0hwjzEA=
